name = "gleam_bbmustache"
description = "Templates in Gleam using bbmustache"
docs_url = "https://hexdocs.pm/gleam_bbmustache/"
repo_url = "https://github.com/gleam-experiments/bbmustache"
category = ""
