name = "gleam_cowboy_websockets"
description = "An expermimental Gleam library for playing with Cowboy websockets"
docs_url = "https://hexdocs.pm/gleam_cowboy_websockets/"
repo_url = "https://github.com/vstreame/gleam_cowboy_websockets"
category = ""
