name = "lustre"
description = "An Elm-inspired framework for building web apps in Gleam!"
docs_url = "https://hexdocs.pm/lustre/"
repo_url = "https://github.com/lustre-labs/lustre"
category = "Frontend"
