name = "parser_gleam"
description = "A porting of parser-ts, purescript-eulalie to Gleam"
docs_url = "https://hexdocs.pm/parser_gleam/"
repo_url = "https://github.com/lucasavila00/parser_gleam"
category = ""
