name = "repeatedly"
description = "Call a function repeatedly with a delay between each call"
docs_url = "https://hexdocs.pm/repeatedly/"
repo_url = "https://github.com/lpil/repeatedly"
category = ""
