name = "sprocket"
description = "A library for building live views and real-time server components in Gleam"
docs_url = "https://hexdocs.pm/sprocket/"
repo_url = "https://github.com/bitbldr/sprocket"
category = ""
