name = "testbldr"
description = "A library for programatically building and running test cases"
docs_url = "https://hexdocs.pm/testbldr/"
repo_url = "https://github.com/bcpeinhardt/testbldr"
category = ""
