name = "transparent_http"
description = "Simple HTTP client to power API wrappers written in Gleam"
docs_url = "https://hexdocs.pm/transparent_http/"
repo_url = "https://github.com/HarryET/transparent_http"
category = ""
